const Router = require('express').Router()
const AuthRouter = require('./AuthRouter')
const CoursesRouter = require('./CoursesRouter')
const GradesRouter = require('./GradesRouter')
const StudentsRouter = require('/StudentsRouter')
Router.use('/', AuthRouter)
Router.use('/course', CoursesRouter)
Router.use('/grades', GradesRouter)
Router.use('/students', StudentsRouter)
module.exports = Router