const Router = require('express').Router()
const AuthRouter = require('./AuthRouter')
const CourseRouter = require('./CourseRouter')
const GradeRouter = require('./GradeRouter')
const StudentRouter = require('./StudentRouter')
Router.use('/', AuthRouter)
Router.use('/courses', CourseRouter)
Router.use('/grades', GradeRouter)
Router.use('/students', StudentRouter)
module.exports = Router